# Generated by Django 6.0.3 on 2026-04-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('t_notificacion', models.CharField(choices=[('action_executer', 'Action Executer'), ('action_receiver', 'Action Receiver'), ('action_controller', 'Action Controller')], default='action_receiver', max_length=30)),
            ],
            options={
                'db_table': 'Notificacion',
            },
        ),
    ]
