# Generated by Django 6.0.3 on 2026-04-02 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Admin')], default='usuario', max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='UsuarioNotificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_recibida', models.DateTimeField(auto_now_add=True)),
                ('id_notificacion', models.ForeignKey(db_column='id_notificacion', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_notificaciones', to='notificacion.notificacion')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_notificaciones', to='usuario.usuario')),
            ],
            options={
                'db_table': 'UsuarioNotificacion',
                'unique_together': {('id_usuario', 'id_notificacion')},
            },
        ),
    ]
