# Generated by Django 6.0.3 on 2026-04-02 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('supermercado', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPromocion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
            ],
            options={
                'db_table': 'TipoPromocion',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=500)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.IntegerField(blank=True, null=True)),
                ('condicion_producto', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado'), ('reacondicionado', 'Reacondicionado')], default='nuevo', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_vigencia', models.CharField(choices=[('por_fecha', 'Por Fecha'), ('permanente', 'Permanente')], default='por_fecha', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('vistas', models.IntegerField(default=0)),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='categoria.categoria')),
                ('id_supermercado', models.ForeignKey(blank=True, db_column='id_supermercado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='supermercado.supermercado')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='usuario.usuario')),
                ('id_tipo_promocion', models.ForeignKey(blank=True, db_column='id_tipo_promocion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='promocion.tipopromocion')),
            ],
            options={
                'db_table': 'Promocion',
            },
        ),
        migrations.CreateModel(
            name='PromocionHorario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miercoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sabado'), ('domingo', 'Domingo')], max_length=15)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('codigo_promocion', models.ForeignKey(db_column='codigo_promocion', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='promocion.promocion')),
            ],
            options={
                'db_table': 'PromocionHorario',
            },
        ),
    ]
