# Generated by Django 5.2.7 on 2026-04-02 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promocion', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('positiva', 'Positiva'), ('negativa', 'Negativa')], max_length=20)),
                ('codigo_promocion', models.ForeignKey(blank=True, db_column='codigo_promocion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='promocion.promocion')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='usuario.usuario')),
            ],
            options={
                'db_table': 'Valoracion',
                'unique_together': {('id_usuario', 'codigo_promocion')},
            },
        ),
    ]
