// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZPszZfiWqEa0SKTkJkBrJjXpEs-BeRZc',
    appId: '1:160922851464:web:aee6a4a9683d6d987fe73d',
    messagingSenderId: '160922851464',
    projectId: 'promomania-page',
    authDomain: 'promomania-page.firebaseapp.com',
    storageBucket: 'promomania-page.firebasestorage.app',
    measurementId: 'G-H9SY0VB2DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-P4YaKGc7frycRGjPCdYYEc-nrn-dfEI',
    appId: '1:160922851464:android:6adb058ac02cb5037fe73d',
    messagingSenderId: '160922851464',
    projectId: 'promomania-page',
    storageBucket: 'promomania-page.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8OynrLMtMY4BmamgdAJSKkB5kjXT_oow',
    appId: '1:160922851464:ios:9fa7f88d22e659947fe73d',
    messagingSenderId: '160922851464',
    projectId: 'promomania-page',
    storageBucket: 'promomania-page.firebasestorage.app',
    iosBundleId: 'com.promomania.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8OynrLMtMY4BmamgdAJSKkB5kjXT_oow',
    appId: '1:160922851464:ios:9fa7f88d22e659947fe73d',
    messagingSenderId: '160922851464',
    projectId: 'promomania-page',
    storageBucket: 'promomania-page.firebasestorage.app',
    iosBundleId: 'com.promomania.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZPszZfiWqEa0SKTkJkBrJjXpEs-BeRZc',
    appId: '1:160922851464:web:959c8670b71393667fe73d',
    messagingSenderId: '160922851464',
    projectId: 'promomania-page',
    authDomain: 'promomania-page.firebaseapp.com',
    storageBucket: 'promomania-page.firebasestorage.app',
    measurementId: 'G-6CXSZ6XDC0',
  );
}
