# Generated by Django 6.0.3 on 2026-04-02 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promocion', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('codigo_promocion', models.ForeignKey(db_column='codigo_promocion', on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='promocion.promocion')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='usuario.usuario')),
            ],
            options={
                'db_table': 'Favorito',
                'unique_together': {('id_usuario', 'codigo_promocion')},
            },
        ),
    ]
