# Generated by Django 6.0.3 on 2026-04-02 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promocion', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('descartado', 'Descartado')], default='pendiente', max_length=20)),
                ('codigo_promocion', models.ForeignKey(db_column='codigo_promocion', on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='promocion.promocion')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='usuario.usuario')),
            ],
            options={
                'db_table': 'Reporte',
            },
        ),
    ]
