# Generated by Django 6.0.3 on 2026-04-02 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promocion', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('codigo_promocion', models.ForeignKey(blank=True, db_column='codigo_promocion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='promocion.promocion')),
                ('id_comment_reply', models.ForeignKey(blank=True, db_column='id_comment_reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='comentario.comentario')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='usuario.usuario')),
            ],
            options={
                'db_table': 'Comentario',
            },
        ),
    ]
